version: '3.6'
services:
    frontend:
        image: 172.12.0.1:5000/${VERSION}
        ports:
            -80:80
        deploy:
            replicas: 1
            restart_policy:
                condition: on failure
        #container_name: tpi
        #env_file: ./constants.env
